version: '3.8'

services:
  db:
    image: postgres:17
    container_name: task_manager_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: task_manager_db
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d task_manager_db"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
