server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: task-manager
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL:jdbc:postgresql://localhost:5433/task_manager_db}
    username: ${DB_USER:admin}
    password: ${DB_PASSWORD:admin123}

  jpa:
    show-sql: true
    generate-ddl: false

  flyway:
    baseline-on-migrate: true
    default-schema: public
    schemas: public
    baseline-version: 0

# JWT token properties for authentication and authorizationAdd commentMore actions
app:
  jwt:
    secret: "77397A24432646294A404E635266556A586E327235753878214125442A472D4B"
    expiration-in-ms: 86400000  # JWT expiration time in milliseconds (24 hours)

    # Internal API key for authentication purposes
  authentication:
    internal-api-key: InternalApiKey1234!

  cors:
    allowed-origins: http://localhost:5173